### ISSUE TITLE
Error when I use the command "gitman install" 

### ISSUE THREAD

**Issue by GengYiran** [jingxixu/dynamic-grasping#1]
![image](https://user-images.githubusercontent.com/75480302/153151887-5efbe29a-bfdb-431c-9d30-fe2e2a42a731.png)

**Comment by GengYiran** [comment]
I'm not the administrator or owner of the repository, so I can't clone with SSH (lack of keys), I don't know if my understanding is correct

**Comment by GengYiran** [comment]
I can change all the git beginnings in the yml file to https format, but this is too troublesome, I want to know if there is any better way

**Comment by GengYiran** [comment]
![image](https://user-images.githubusercontent.com/75480302/153158168-7e1c8977-2a92-4d10-84f1-61b6dbfb3723.png)
Now I meet another problem... I tried opening the link   https://github.com/CRLab/ur5_robotiq_reachability_config.git/   , but got 404

**Comment by jingxixu** [comment]
Hi, this is an access permission issue on our end. We will make those repos public as well.

**Comment by GengYiran** [comment]
Ok! Thank you!

**Comment by GengYiran** [comment]
Thank you for open-sourcing those codes, but I found that there still seem to be 5 packages that are not open-sourced.
![image](https://user-images.githubusercontent.com/75480302/153713849-0d59f7ec-de68-4065-9cb5-2cab52f72351.png)
![image](https://user-images.githubusercontent.com/75480302/153713857-4975ccf0-38a1-4412-a1f5-33dc6bf578f7.png)

**Comment by jingxixu** [comment]
Hi, I don't think these packages are necessary. You should be able to run dynamic grasping without these packages. I will update the gitman file to remove these packages when I have a chance.

**Comment by GengYiran** [comment]
Thank you! I'll close my question.

**Comment by GengYiran** [comment]
Thank you! I'll close my question.
