### ISSUE TITLE
iretiayo/dynamic_grasping_demo Not found

### ISSUE THREAD

**Issue by Bailey-24** [jingxixu/dynamic-grasping#3]
```
 git clone --mirror git@github.com:iretiayo/dynamic_grasping_demo.git /home/pi/.gitcache/dynamic_grasping_demo.reference克隆到纯仓库 '/home/pi/.gitcache/dynamic_grasping_demo.reference'...
ERROR: Repository not found.
fatal: Could not read from remote repository. Please make sure you have the correct access rightsand the repository exists
```
When I ran `gitman install` to setup the project, but I got this error, and I found that this is no existing in the `iretiayo/dynamic_grasping_demo` any more.

So would you please ask iretiayo to put the project `dynamic_grasping_demo` in his repo?

**Comment by jingxixu** [comment]
Hi, thanks for your interest in this repo. The iretiayo/dynamic_grasping_demo is not required any more. You can remove it from gitman.
